package com.zyl.jpa.batch.mapper;

// Generated 2017-3-21 14:02:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CcsCar generated by hbm2java
 */
@Entity
@Table(name = "ccs_car", catalog = "test")
public class CcsCar implements java.io.Serializable {

	private static final long serialVersionUID = -554721083945010309L;

	private Long cardId;
	private String org;
	private Long acctNbr;
	private Character acctType;
	private String applicationNo;
	private String contrNbr;
	private String dealerId;
	private String dealerName;
	private String dealerCompanyId;
	private String dealerCompanyName;
	private String dealerMobileNo;
	private String storeNo;
	private String carBrand;
	private String carLicenseNo;
	private String carModelNo;
	private String transferTimes;
	private String carFrameNo;
	private String carEngineNo;
	private String carColor;
	private BigDecimal travelMileage;
	private Date purchaseTime;
	private BigDecimal purchaseAmt;
	private BigDecimal carPrice;
	private BigDecimal loanAmt;
	private Date bizDate;
	private BigDecimal accessedValue;
	private Character mortgageInd;
	private BigDecimal returnAmt;
	private BigDecimal returnMerFee;
	private Character returnInd;
	private Date returnDate;
	private Date bizTime;
	private Date createTime;
	private String createUser;
	private Date lstUpdTime;
	private String lstUpdUser;
	private Long jpaVersion;
	private BigDecimal gps;
	private String premiumInd;
	private BigDecimal loanServiceFee;

	@Override
	public String toString() {
		return "CcsCar [cardId=" + cardId + ", acctNbr=" + acctNbr
				+ ", contrNbr=" + contrNbr + "]";
	}

	public CcsCar() {
	}

	public CcsCar(String org, Long acctNbr, Character acctType,
			String applicationNo, String contrNbr, String dealerId,
			String dealerName, String dealerCompanyId,
			String dealerCompanyName, String dealerMobileNo, String storeNo,
			String carBrand, String carLicenseNo, String carModelNo,
			String transferTimes, String carFrameNo, String carEngineNo,
			String carColor, BigDecimal travelMileage, Date purchaseTime,
			BigDecimal purchaseAmt, BigDecimal carPrice, BigDecimal loanAmt,
			Date bizDate, BigDecimal accessedValue, Character mortgageInd,
			BigDecimal returnAmt, BigDecimal returnMerFee, Character returnInd,
			Date returnDate, Date bizTime, Date createTime, String createUser,
			Date lstUpdTime, String lstUpdUser, Long jpaVersion,
			BigDecimal gps, String premiumInd, BigDecimal loanServiceFee) {
		this.org = org;
		this.acctNbr = acctNbr;
		this.acctType = acctType;
		this.applicationNo = applicationNo;
		this.contrNbr = contrNbr;
		this.dealerId = dealerId;
		this.dealerName = dealerName;
		this.dealerCompanyId = dealerCompanyId;
		this.dealerCompanyName = dealerCompanyName;
		this.dealerMobileNo = dealerMobileNo;
		this.storeNo = storeNo;
		this.carBrand = carBrand;
		this.carLicenseNo = carLicenseNo;
		this.carModelNo = carModelNo;
		this.transferTimes = transferTimes;
		this.carFrameNo = carFrameNo;
		this.carEngineNo = carEngineNo;
		this.carColor = carColor;
		this.travelMileage = travelMileage;
		this.purchaseTime = purchaseTime;
		this.purchaseAmt = purchaseAmt;
		this.carPrice = carPrice;
		this.loanAmt = loanAmt;
		this.bizDate = bizDate;
		this.accessedValue = accessedValue;
		this.mortgageInd = mortgageInd;
		this.returnAmt = returnAmt;
		this.returnMerFee = returnMerFee;
		this.returnInd = returnInd;
		this.returnDate = returnDate;
		this.bizTime = bizTime;
		this.createTime = createTime;
		this.createUser = createUser;
		this.lstUpdTime = lstUpdTime;
		this.lstUpdUser = lstUpdUser;
		this.jpaVersion = jpaVersion;
		this.gps = gps;
		this.premiumInd = premiumInd;
		this.loanServiceFee = loanServiceFee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CARD_ID", unique = true, nullable = false)
	public Long getCardId() {
		return this.cardId;
	}

	public void setCardId(Long cardId) {
		this.cardId = cardId;
	}

	@Column(name = "ORG", length = 12)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "ACCT_NBR", precision = 16, scale = 0)
	public Long getAcctNbr() {
		return this.acctNbr;
	}

	public void setAcctNbr(Long acctNbr) {
		this.acctNbr = acctNbr;
	}

	@Column(name = "ACCT_TYPE", length = 1)
	public Character getAcctType() {
		return this.acctType;
	}

	public void setAcctType(Character acctType) {
		this.acctType = acctType;
	}

	@Column(name = "APPLICATION_NO", length = 32)
	public String getApplicationNo() {
		return this.applicationNo;
	}

	public void setApplicationNo(String applicationNo) {
		this.applicationNo = applicationNo;
	}

	@Column(name = "CONTR_NBR", length = 50)
	public String getContrNbr() {
		return this.contrNbr;
	}

	public void setContrNbr(String contrNbr) {
		this.contrNbr = contrNbr;
	}

	@Column(name = "DEALER_ID", length = 60)
	public String getDealerId() {
		return this.dealerId;
	}

	public void setDealerId(String dealerId) {
		this.dealerId = dealerId;
	}

	@Column(name = "DEALER_NAME", length = 60)
	public String getDealerName() {
		return this.dealerName;
	}

	public void setDealerName(String dealerName) {
		this.dealerName = dealerName;
	}

	@Column(name = "DEALER_COMPANY_ID", length = 60)
	public String getDealerCompanyId() {
		return this.dealerCompanyId;
	}

	public void setDealerCompanyId(String dealerCompanyId) {
		this.dealerCompanyId = dealerCompanyId;
	}

	@Column(name = "DEALER_COMPANY_NAME", length = 60)
	public String getDealerCompanyName() {
		return this.dealerCompanyName;
	}

	public void setDealerCompanyName(String dealerCompanyName) {
		this.dealerCompanyName = dealerCompanyName;
	}

	@Column(name = "DEALER_MOBILE_NO", length = 60)
	public String getDealerMobileNo() {
		return this.dealerMobileNo;
	}

	public void setDealerMobileNo(String dealerMobileNo) {
		this.dealerMobileNo = dealerMobileNo;
	}

	@Column(name = "STORE_NO", length = 60)
	public String getStoreNo() {
		return this.storeNo;
	}

	public void setStoreNo(String storeNo) {
		this.storeNo = storeNo;
	}

	@Column(name = "CAR_BRAND", length = 80)
	public String getCarBrand() {
		return this.carBrand;
	}

	public void setCarBrand(String carBrand) {
		this.carBrand = carBrand;
	}

	@Column(name = "CAR_LICENSE_NO", length = 30)
	public String getCarLicenseNo() {
		return this.carLicenseNo;
	}

	public void setCarLicenseNo(String carLicenseNo) {
		this.carLicenseNo = carLicenseNo;
	}

	@Column(name = "CAR_MODEL_NO", length = 30)
	public String getCarModelNo() {
		return this.carModelNo;
	}

	public void setCarModelNo(String carModelNo) {
		this.carModelNo = carModelNo;
	}

	@Column(name = "TRANSFER_TIMES", length = 10)
	public String getTransferTimes() {
		return this.transferTimes;
	}

	public void setTransferTimes(String transferTimes) {
		this.transferTimes = transferTimes;
	}

	@Column(name = "CAR_FRAME_NO", length = 30)
	public String getCarFrameNo() {
		return this.carFrameNo;
	}

	public void setCarFrameNo(String carFrameNo) {
		this.carFrameNo = carFrameNo;
	}

	@Column(name = "CAR_ENGINE_NO", length = 30)
	public String getCarEngineNo() {
		return this.carEngineNo;
	}

	public void setCarEngineNo(String carEngineNo) {
		this.carEngineNo = carEngineNo;
	}

	@Column(name = "CAR_COLOR", length = 10)
	public String getCarColor() {
		return this.carColor;
	}

	public void setCarColor(String carColor) {
		this.carColor = carColor;
	}

	@Column(name = "TRAVEL_MILEAGE", precision = 15)
	public BigDecimal getTravelMileage() {
		return this.travelMileage;
	}

	public void setTravelMileage(BigDecimal travelMileage) {
		this.travelMileage = travelMileage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PURCHASE_TIME", length = 10)
	public Date getPurchaseTime() {
		return this.purchaseTime;
	}

	public void setPurchaseTime(Date purchaseTime) {
		this.purchaseTime = purchaseTime;
	}

	@Column(name = "PURCHASE_AMT", precision = 15)
	public BigDecimal getPurchaseAmt() {
		return this.purchaseAmt;
	}

	public void setPurchaseAmt(BigDecimal purchaseAmt) {
		this.purchaseAmt = purchaseAmt;
	}

	@Column(name = "CAR_PRICE", precision = 15)
	public BigDecimal getCarPrice() {
		return this.carPrice;
	}

	public void setCarPrice(BigDecimal carPrice) {
		this.carPrice = carPrice;
	}

	@Column(name = "LOAN_AMT", precision = 15)
	public BigDecimal getLoanAmt() {
		return this.loanAmt;
	}

	public void setLoanAmt(BigDecimal loanAmt) {
		this.loanAmt = loanAmt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIZ_DATE", length = 10)
	public Date getBizDate() {
		return this.bizDate;
	}

	public void setBizDate(Date bizDate) {
		this.bizDate = bizDate;
	}

	@Column(name = "ACCESSED_VALUE", precision = 15)
	public BigDecimal getAccessedValue() {
		return this.accessedValue;
	}

	public void setAccessedValue(BigDecimal accessedValue) {
		this.accessedValue = accessedValue;
	}

	@Column(name = "MORTGAGE_IND", length = 1)
	public Character getMortgageInd() {
		return this.mortgageInd;
	}

	public void setMortgageInd(Character mortgageInd) {
		this.mortgageInd = mortgageInd;
	}

	@Column(name = "RETURN_AMT", precision = 15)
	public BigDecimal getReturnAmt() {
		return this.returnAmt;
	}

	public void setReturnAmt(BigDecimal returnAmt) {
		this.returnAmt = returnAmt;
	}

	@Column(name = "RETURN_MER_FEE", precision = 15)
	public BigDecimal getReturnMerFee() {
		return this.returnMerFee;
	}

	public void setReturnMerFee(BigDecimal returnMerFee) {
		this.returnMerFee = returnMerFee;
	}

	@Column(name = "RETURN_IND", length = 1)
	public Character getReturnInd() {
		return this.returnInd;
	}

	public void setReturnInd(Character returnInd) {
		this.returnInd = returnInd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RETURN_DATE", length = 10)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIZ_TIME", length = 19)
	public Date getBizTime() {
		return this.bizTime;
	}

	public void setBizTime(Date bizTime) {
		this.bizTime = bizTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CREATE_USER", length = 32)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPD_TIME", length = 19)
	public Date getLstUpdTime() {
		return this.lstUpdTime;
	}

	public void setLstUpdTime(Date lstUpdTime) {
		this.lstUpdTime = lstUpdTime;
	}

	@Column(name = "LST_UPD_USER", length = 32)
	public String getLstUpdUser() {
		return this.lstUpdUser;
	}

	public void setLstUpdUser(String lstUpdUser) {
		this.lstUpdUser = lstUpdUser;
	}

	@Column(name = "JPA_VERSION", precision = 10, scale = 0)
	public Long getJpaVersion() {
		return this.jpaVersion;
	}

	public void setJpaVersion(Long jpaVersion) {
		this.jpaVersion = jpaVersion;
	}

	@Column(name = "GPS", precision = 6)
	public BigDecimal getGps() {
		return this.gps;
	}

	public void setGps(BigDecimal gps) {
		this.gps = gps;
	}

	@Column(name = "PREMIUM_IND", length = 1)
	public String getPremiumInd() {
		return this.premiumInd;
	}

	public void setPremiumInd(String premiumInd) {
		this.premiumInd = premiumInd;
	}

	@Column(name = "LOAN_SERVICE_FEE", precision = 15)
	public BigDecimal getLoanServiceFee() {
		return this.loanServiceFee;
	}

	public void setLoanServiceFee(BigDecimal loanServiceFee) {
		this.loanServiceFee = loanServiceFee;
	}

}
