package com.zyl.jpa.domain;

// Generated 2017-3-20 11:25:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CcsAcctNbr generated by hbm2java
 */
@Entity
@Table(name = "ccs_acct_nbr", catalog = "test")
public class CcsAcctNbr implements java.io.Serializable {

	private Long acctNbr;
	private String org;
	private Date createTime;
	private String createUser;
	private Date lstUpdTime;
	private String lstUpdUser;
	private long jpaVersion;

	public CcsAcctNbr() {
	}

	public CcsAcctNbr(String org, long jpaVersion) {
		this.org = org;
		this.jpaVersion = jpaVersion;
	}

	public CcsAcctNbr(String org, Date createTime, String createUser,
			Date lstUpdTime, String lstUpdUser, long jpaVersion) {
		this.org = org;
		this.createTime = createTime;
		this.createUser = createUser;
		this.lstUpdTime = lstUpdTime;
		this.lstUpdUser = lstUpdUser;
		this.jpaVersion = jpaVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACCT_NBR", unique = true, nullable = false)
	public Long getAcctNbr() {
		return this.acctNbr;
	}

	public void setAcctNbr(Long acctNbr) {
		this.acctNbr = acctNbr;
	}

	@Column(name = "ORG", nullable = false, length = 12)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CREATE_USER", length = 32)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPD_TIME", length = 19)
	public Date getLstUpdTime() {
		return this.lstUpdTime;
	}

	public void setLstUpdTime(Date lstUpdTime) {
		this.lstUpdTime = lstUpdTime;
	}

	@Column(name = "LST_UPD_USER", length = 32)
	public String getLstUpdUser() {
		return this.lstUpdUser;
	}

	public void setLstUpdUser(String lstUpdUser) {
		this.lstUpdUser = lstUpdUser;
	}

	@Column(name = "JPA_VERSION", nullable = false, precision = 10, scale = 0)
	public long getJpaVersion() {
		return this.jpaVersion;
	}

	public void setJpaVersion(long jpaVersion) {
		this.jpaVersion = jpaVersion;
	}

}
