package com.zyl.jpa.domain;

// Generated 2017-5-5 14:31:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CcsAcctId generated by hbm2java
 */
@Embeddable
public class CcsAcctId implements java.io.Serializable {

	private long acctNbr;
	private char acctType;

	public CcsAcctId() {
	}

	public CcsAcctId(long acctNbr, char acctType) {
		this.acctNbr = acctNbr;
		this.acctType = acctType;
	}

	@Column(name = "ACCT_NBR", nullable = false)
	public long getAcctNbr() {
		return this.acctNbr;
	}

	public void setAcctNbr(long acctNbr) {
		this.acctNbr = acctNbr;
	}

	@Column(name = "ACCT_TYPE", nullable = false, length = 1)
	public char getAcctType() {
		return this.acctType;
	}

	public void setAcctType(char acctType) {
		this.acctType = acctType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CcsAcctId))
			return false;
		CcsAcctId castOther = (CcsAcctId) other;

		return (this.getAcctNbr() == castOther.getAcctNbr())
				&& (this.getAcctType() == castOther.getAcctType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAcctNbr();
		result = 37 * result + this.getAcctType();
		return result;
	}

}
