package com.zyl.jpa.domain;

// Generated 2017-5-5 14:31:14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CcsAcctingMerge generated by hbm2java
 */
@Entity
@Table(name = "ccs_accting_merge", catalog = "test")
public class CcsAcctingMerge implements java.io.Serializable {

	private Long mergeId;
	private String org;
	private String glOrg;
	private String glOrgName;
	private String glVoucherId;
	private String glVoucherType;
	private String fiscalYear;
	private String accountingPeriod;
	private Date businessDate;
	private String currency;
	private String subjectCd;
	private String subjectName;
	private String subjectDesc;
	private BigDecimal subjectDebitAmt;
	private BigDecimal subjectCreditAmt;
	private String auxiliaryAccounting;
	private Date createTime;
	private String createUser;
	private String lstUpdUser;
	private Date lstUpdTime;
	private Long jpaVersion;
	private String glVoucherGroup;

	public CcsAcctingMerge() {
	}

	public CcsAcctingMerge(String org, String glOrg, String glOrgName,
			String glVoucherId, String glVoucherType, String fiscalYear,
			String accountingPeriod, Date businessDate, String currency,
			String subjectCd, String subjectName, String subjectDesc,
			BigDecimal subjectDebitAmt, BigDecimal subjectCreditAmt,
			String auxiliaryAccounting, Date createTime, String createUser,
			String lstUpdUser, Date lstUpdTime, Long jpaVersion,
			String glVoucherGroup) {
		this.org = org;
		this.glOrg = glOrg;
		this.glOrgName = glOrgName;
		this.glVoucherId = glVoucherId;
		this.glVoucherType = glVoucherType;
		this.fiscalYear = fiscalYear;
		this.accountingPeriod = accountingPeriod;
		this.businessDate = businessDate;
		this.currency = currency;
		this.subjectCd = subjectCd;
		this.subjectName = subjectName;
		this.subjectDesc = subjectDesc;
		this.subjectDebitAmt = subjectDebitAmt;
		this.subjectCreditAmt = subjectCreditAmt;
		this.auxiliaryAccounting = auxiliaryAccounting;
		this.createTime = createTime;
		this.createUser = createUser;
		this.lstUpdUser = lstUpdUser;
		this.lstUpdTime = lstUpdTime;
		this.jpaVersion = jpaVersion;
		this.glVoucherGroup = glVoucherGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MERGE_ID", unique = true, nullable = false)
	public Long getMergeId() {
		return this.mergeId;
	}

	public void setMergeId(Long mergeId) {
		this.mergeId = mergeId;
	}

	@Column(name = "ORG", length = 12)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "GL_ORG", length = 32)
	public String getGlOrg() {
		return this.glOrg;
	}

	public void setGlOrg(String glOrg) {
		this.glOrg = glOrg;
	}

	@Column(name = "GL_ORG_NAME", length = 100)
	public String getGlOrgName() {
		return this.glOrgName;
	}

	public void setGlOrgName(String glOrgName) {
		this.glOrgName = glOrgName;
	}

	@Column(name = "GL_VOUCHER_ID", length = 20)
	public String getGlVoucherId() {
		return this.glVoucherId;
	}

	public void setGlVoucherId(String glVoucherId) {
		this.glVoucherId = glVoucherId;
	}

	@Column(name = "GL_VOUCHER_TYPE", length = 10)
	public String getGlVoucherType() {
		return this.glVoucherType;
	}

	public void setGlVoucherType(String glVoucherType) {
		this.glVoucherType = glVoucherType;
	}

	@Column(name = "FISCAL_YEAR", length = 10)
	public String getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(String fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "ACCOUNTING_PERIOD", length = 2)
	public String getAccountingPeriod() {
		return this.accountingPeriod;
	}

	public void setAccountingPeriod(String accountingPeriod) {
		this.accountingPeriod = accountingPeriod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BUSINESS_DATE", length = 10)
	public Date getBusinessDate() {
		return this.businessDate;
	}

	public void setBusinessDate(Date businessDate) {
		this.businessDate = businessDate;
	}

	@Column(name = "CURRENCY", length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "SUBJECT_CD", length = 12)
	public String getSubjectCd() {
		return this.subjectCd;
	}

	public void setSubjectCd(String subjectCd) {
		this.subjectCd = subjectCd;
	}

	@Column(name = "SUBJECT_NAME", length = 100)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "SUBJECT_DESC", length = 200)
	public String getSubjectDesc() {
		return this.subjectDesc;
	}

	public void setSubjectDesc(String subjectDesc) {
		this.subjectDesc = subjectDesc;
	}

	@Column(name = "SUBJECT_DEBIT_AMT", precision = 15)
	public BigDecimal getSubjectDebitAmt() {
		return this.subjectDebitAmt;
	}

	public void setSubjectDebitAmt(BigDecimal subjectDebitAmt) {
		this.subjectDebitAmt = subjectDebitAmt;
	}

	@Column(name = "SUBJECT_CREDIT_AMT", precision = 15)
	public BigDecimal getSubjectCreditAmt() {
		return this.subjectCreditAmt;
	}

	public void setSubjectCreditAmt(BigDecimal subjectCreditAmt) {
		this.subjectCreditAmt = subjectCreditAmt;
	}

	@Column(name = "AUXILIARY_ACCOUNTING", length = 100)
	public String getAuxiliaryAccounting() {
		return this.auxiliaryAccounting;
	}

	public void setAuxiliaryAccounting(String auxiliaryAccounting) {
		this.auxiliaryAccounting = auxiliaryAccounting;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CREATE_USER", length = 32)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "LST_UPD_USER", length = 32)
	public String getLstUpdUser() {
		return this.lstUpdUser;
	}

	public void setLstUpdUser(String lstUpdUser) {
		this.lstUpdUser = lstUpdUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPD_TIME", length = 19)
	public Date getLstUpdTime() {
		return this.lstUpdTime;
	}

	public void setLstUpdTime(Date lstUpdTime) {
		this.lstUpdTime = lstUpdTime;
	}

	@Column(name = "JPA_VERSION", precision = 10, scale = 0)
	public Long getJpaVersion() {
		return this.jpaVersion;
	}

	public void setJpaVersion(Long jpaVersion) {
		this.jpaVersion = jpaVersion;
	}

	@Column(name = "GL_VOUCHER_GROUP", length = 20)
	public String getGlVoucherGroup() {
		return this.glVoucherGroup;
	}

	public void setGlVoucherGroup(String glVoucherGroup) {
		this.glVoucherGroup = glVoucherGroup;
	}

}
