package com.zyl.jpa.domain;

// Generated 2017-5-5 14:31:14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CcsAcctingEntry generated by hbm2java
 */
@Entity
@Table(name = "ccs_accting_entry", catalog = "test")
public class CcsAcctingEntry implements java.io.Serializable {

	private Long txnId;
	private String org;
	private String glOrg;
	private String loanCode;
	private String currency;
	private String origTxnSeq;
	private long acctNbr;
	private char acctType;
	private String contrNbr;
	private String dueBillNo;
	private char acctStatus;
	private char ageCodeGl;
	private Character preAgeCodeGl;
	private String txnCode;
	private char dbCrInd;
	private String subjectCd;
	private String subjectName;
	private String subjectDirct;
	private String subjectRbInd;
	private String subjectDesc;
	private String checkMark;
	private Date postDate;
	private BigDecimal postAmt;
	private String owningBranch;
	private String glVoucherId;
	private Date createTime;
	private String createUser;
	private Date lstUpdTime;
	private String lstUpdUser;
	private long jpaVersion;
	private String glVoucherGroup;
	private String paymentChannelCd;
	private String paymentTraceNbr;
	private Character isOffset;
	private Long orderId;

	public CcsAcctingEntry() {
	}

	public CcsAcctingEntry(String org, String glOrg, String loanCode,
			String currency, String origTxnSeq, long acctNbr, char acctType,
			String contrNbr, String dueBillNo, char acctStatus, char ageCodeGl,
			String txnCode, char dbCrInd, String subjectCd,
			String subjectDirct, String subjectRbInd, Date postDate,
			BigDecimal postAmt, long jpaVersion) {
		this.org = org;
		this.glOrg = glOrg;
		this.loanCode = loanCode;
		this.currency = currency;
		this.origTxnSeq = origTxnSeq;
		this.acctNbr = acctNbr;
		this.acctType = acctType;
		this.contrNbr = contrNbr;
		this.dueBillNo = dueBillNo;
		this.acctStatus = acctStatus;
		this.ageCodeGl = ageCodeGl;
		this.txnCode = txnCode;
		this.dbCrInd = dbCrInd;
		this.subjectCd = subjectCd;
		this.subjectDirct = subjectDirct;
		this.subjectRbInd = subjectRbInd;
		this.postDate = postDate;
		this.postAmt = postAmt;
		this.jpaVersion = jpaVersion;
	}

	public CcsAcctingEntry(String org, String glOrg, String loanCode,
			String currency, String origTxnSeq, long acctNbr, char acctType,
			String contrNbr, String dueBillNo, char acctStatus, char ageCodeGl,
			Character preAgeCodeGl, String txnCode, char dbCrInd,
			String subjectCd, String subjectName, String subjectDirct,
			String subjectRbInd, String subjectDesc, String checkMark,
			Date postDate, BigDecimal postAmt, String owningBranch,
			String glVoucherId, Date createTime, String createUser,
			Date lstUpdTime, String lstUpdUser, long jpaVersion,
			String glVoucherGroup, String paymentChannelCd,
			String paymentTraceNbr, Character isOffset, Long orderId) {
		this.org = org;
		this.glOrg = glOrg;
		this.loanCode = loanCode;
		this.currency = currency;
		this.origTxnSeq = origTxnSeq;
		this.acctNbr = acctNbr;
		this.acctType = acctType;
		this.contrNbr = contrNbr;
		this.dueBillNo = dueBillNo;
		this.acctStatus = acctStatus;
		this.ageCodeGl = ageCodeGl;
		this.preAgeCodeGl = preAgeCodeGl;
		this.txnCode = txnCode;
		this.dbCrInd = dbCrInd;
		this.subjectCd = subjectCd;
		this.subjectName = subjectName;
		this.subjectDirct = subjectDirct;
		this.subjectRbInd = subjectRbInd;
		this.subjectDesc = subjectDesc;
		this.checkMark = checkMark;
		this.postDate = postDate;
		this.postAmt = postAmt;
		this.owningBranch = owningBranch;
		this.glVoucherId = glVoucherId;
		this.createTime = createTime;
		this.createUser = createUser;
		this.lstUpdTime = lstUpdTime;
		this.lstUpdUser = lstUpdUser;
		this.jpaVersion = jpaVersion;
		this.glVoucherGroup = glVoucherGroup;
		this.paymentChannelCd = paymentChannelCd;
		this.paymentTraceNbr = paymentTraceNbr;
		this.isOffset = isOffset;
		this.orderId = orderId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TXN_ID", unique = true, nullable = false)
	public Long getTxnId() {
		return this.txnId;
	}

	public void setTxnId(Long txnId) {
		this.txnId = txnId;
	}

	@Column(name = "ORG", nullable = false, length = 12)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "GL_ORG", nullable = false, length = 32)
	public String getGlOrg() {
		return this.glOrg;
	}

	public void setGlOrg(String glOrg) {
		this.glOrg = glOrg;
	}

	@Column(name = "LOAN_CODE", nullable = false, length = 4)
	public String getLoanCode() {
		return this.loanCode;
	}

	public void setLoanCode(String loanCode) {
		this.loanCode = loanCode;
	}

	@Column(name = "CURRENCY", nullable = false, length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "ORIG_TXN_SEQ", nullable = false, length = 64)
	public String getOrigTxnSeq() {
		return this.origTxnSeq;
	}

	public void setOrigTxnSeq(String origTxnSeq) {
		this.origTxnSeq = origTxnSeq;
	}

	@Column(name = "ACCT_NBR", nullable = false, precision = 16, scale = 0)
	public long getAcctNbr() {
		return this.acctNbr;
	}

	public void setAcctNbr(long acctNbr) {
		this.acctNbr = acctNbr;
	}

	@Column(name = "ACCT_TYPE", nullable = false, length = 1)
	public char getAcctType() {
		return this.acctType;
	}

	public void setAcctType(char acctType) {
		this.acctType = acctType;
	}

	@Column(name = "CONTR_NBR", nullable = false, length = 50)
	public String getContrNbr() {
		return this.contrNbr;
	}

	public void setContrNbr(String contrNbr) {
		this.contrNbr = contrNbr;
	}

	@Column(name = "DUE_BILL_NO", nullable = false, length = 32)
	public String getDueBillNo() {
		return this.dueBillNo;
	}

	public void setDueBillNo(String dueBillNo) {
		this.dueBillNo = dueBillNo;
	}

	@Column(name = "ACCT_STATUS", nullable = false, length = 1)
	public char getAcctStatus() {
		return this.acctStatus;
	}

	public void setAcctStatus(char acctStatus) {
		this.acctStatus = acctStatus;
	}

	@Column(name = "AGE_CODE_GL", nullable = false, length = 1)
	public char getAgeCodeGl() {
		return this.ageCodeGl;
	}

	public void setAgeCodeGl(char ageCodeGl) {
		this.ageCodeGl = ageCodeGl;
	}

	@Column(name = "PRE_AGE_CODE_GL", length = 1)
	public Character getPreAgeCodeGl() {
		return this.preAgeCodeGl;
	}

	public void setPreAgeCodeGl(Character preAgeCodeGl) {
		this.preAgeCodeGl = preAgeCodeGl;
	}

	@Column(name = "TXN_CODE", nullable = false, length = 4)
	public String getTxnCode() {
		return this.txnCode;
	}

	public void setTxnCode(String txnCode) {
		this.txnCode = txnCode;
	}

	@Column(name = "DB_CR_IND", nullable = false, length = 1)
	public char getDbCrInd() {
		return this.dbCrInd;
	}

	public void setDbCrInd(char dbCrInd) {
		this.dbCrInd = dbCrInd;
	}

	@Column(name = "SUBJECT_CD", nullable = false, length = 12)
	public String getSubjectCd() {
		return this.subjectCd;
	}

	public void setSubjectCd(String subjectCd) {
		this.subjectCd = subjectCd;
	}

	@Column(name = "SUBJECT_NAME", length = 100)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "SUBJECT_DIRCT", nullable = false, length = 12)
	public String getSubjectDirct() {
		return this.subjectDirct;
	}

	public void setSubjectDirct(String subjectDirct) {
		this.subjectDirct = subjectDirct;
	}

	@Column(name = "SUBJECT_RB_IND", nullable = false, length = 12)
	public String getSubjectRbInd() {
		return this.subjectRbInd;
	}

	public void setSubjectRbInd(String subjectRbInd) {
		this.subjectRbInd = subjectRbInd;
	}

	@Column(name = "SUBJECT_DESC", length = 200)
	public String getSubjectDesc() {
		return this.subjectDesc;
	}

	public void setSubjectDesc(String subjectDesc) {
		this.subjectDesc = subjectDesc;
	}

	@Column(name = "CHECK_MARK", length = 20)
	public String getCheckMark() {
		return this.checkMark;
	}

	public void setCheckMark(String checkMark) {
		this.checkMark = checkMark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "POST_DATE", nullable = false, length = 10)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Column(name = "POST_AMT", nullable = false, precision = 15)
	public BigDecimal getPostAmt() {
		return this.postAmt;
	}

	public void setPostAmt(BigDecimal postAmt) {
		this.postAmt = postAmt;
	}

	@Column(name = "OWNING_BRANCH", length = 32)
	public String getOwningBranch() {
		return this.owningBranch;
	}

	public void setOwningBranch(String owningBranch) {
		this.owningBranch = owningBranch;
	}

	@Column(name = "GL_VOUCHER_ID", length = 20)
	public String getGlVoucherId() {
		return this.glVoucherId;
	}

	public void setGlVoucherId(String glVoucherId) {
		this.glVoucherId = glVoucherId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CREATE_USER", length = 32)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPD_TIME", length = 19)
	public Date getLstUpdTime() {
		return this.lstUpdTime;
	}

	public void setLstUpdTime(Date lstUpdTime) {
		this.lstUpdTime = lstUpdTime;
	}

	@Column(name = "LST_UPD_USER", length = 32)
	public String getLstUpdUser() {
		return this.lstUpdUser;
	}

	public void setLstUpdUser(String lstUpdUser) {
		this.lstUpdUser = lstUpdUser;
	}

	@Column(name = "JPA_VERSION", nullable = false, precision = 10, scale = 0)
	public long getJpaVersion() {
		return this.jpaVersion;
	}

	public void setJpaVersion(long jpaVersion) {
		this.jpaVersion = jpaVersion;
	}

	@Column(name = "GL_VOUCHER_GROUP", length = 20)
	public String getGlVoucherGroup() {
		return this.glVoucherGroup;
	}

	public void setGlVoucherGroup(String glVoucherGroup) {
		this.glVoucherGroup = glVoucherGroup;
	}

	@Column(name = "PAYMENT_CHANNEL_CD", length = 20)
	public String getPaymentChannelCd() {
		return this.paymentChannelCd;
	}

	public void setPaymentChannelCd(String paymentChannelCd) {
		this.paymentChannelCd = paymentChannelCd;
	}

	@Column(name = "PAYMENT_TRACE_NBR", length = 50)
	public String getPaymentTraceNbr() {
		return this.paymentTraceNbr;
	}

	public void setPaymentTraceNbr(String paymentTraceNbr) {
		this.paymentTraceNbr = paymentTraceNbr;
	}

	@Column(name = "IS_OFFSET", length = 1)
	public Character getIsOffset() {
		return this.isOffset;
	}

	public void setIsOffset(Character isOffset) {
		this.isOffset = isOffset;
	}

	@Column(name = "ORDER_ID", precision = 16, scale = 0)
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

}
