package com.zyl.jpa.domain;

// Generated 2017-3-20 11:25:31 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CcsOrder generated by hbm2java
 */
@Entity
@Table(name = "ccs_order", catalog = "test")
public class CcsOrder implements java.io.Serializable {

	private Long orderId;
	private String org;
	private String channelId;
	private Long logKv;
	private Long acctNbr;
	private Character acctType;
	private String commandType;
	private String orderBrief;
	private Character orderStatus;
	private Date orderTime;
	private Date orberFailTime;
	private String merId;
	private String merName;
	private String productType;
	private String txnType;
	private BigDecimal txnAmt;
	private String currency;
	private String openBankId;
	private String openBank;
	private Character cardType;
	private String cardNo;
	private String usrName;
	private String certType;
	private String certId;
	private String purpose;
	private String priv1;
	private String state;
	private String city;
	private String subBank;
	private String flag;
	private String guarantyId;
	private String status;
	private String code;
	private String message;
	private String dueBillNo;
	private Date businessDate;
	private Date sendTime;
	private Long oriOrderId;
	private Date setupDate;
	private Date optDatetime;
	private String loanUsage;
	private String payChannelId;
	private String payBizCode;
	private BigDecimal successAmt;
	private BigDecimal failureAmt;
	private Character onlineFlag;
	private String requestTime;
	private String servicesn;
	private String authTxnTerminal;
	private String acqId;
	private Character matchInd;
	private Character comparedInd;
	private Character errInd;
	private String memo;
	private Date createTime;
	private String createUser;
	private Date lstUpdTime;
	private String lstUpdUser;
	private Long jpaVersion;
	private String subTerminalType;
	private String contrNbr;
	private String mobileNumber;
	private String refNbr;
	private String contactChnl;
	private String serviceId;
	private String merchandiseOrder;
	private String responseCode;
	private String responseMessage;
	private String terminalDevice;
	private BigDecimal premiumAmt;
	private Character premiumInd;
	private BigDecimal loanAmt;
	private String couponId;
	private Character offsetType;
	private Long term;
	private String loanProdGroup;
	private String proofId;
	private String paymentChannel;
	private Integer loanAgainTimes;
	private String payTerms;

	public CcsOrder() {
	}

	public CcsOrder(String org, String channelId, Long logKv, Long acctNbr,
			Character acctType, String commandType, String orderBrief,
			Character orderStatus, Date orderTime, Date orberFailTime,
			String merId, String merName, String productType, String txnType,
			BigDecimal txnAmt, String currency, String openBankId,
			String openBank, Character cardType, String cardNo, String usrName,
			String certType, String certId, String purpose, String priv1,
			String state, String city, String subBank, String flag,
			String guarantyId, String status, String code, String message,
			String dueBillNo, Date businessDate, Date sendTime,
			Long oriOrderId, Date setupDate, Date optDatetime,
			String loanUsage, String payChannelId, String payBizCode,
			BigDecimal successAmt, BigDecimal failureAmt, Character onlineFlag,
			String requestTime, String servicesn, String authTxnTerminal,
			String acqId, Character matchInd, Character comparedInd,
			Character errInd, String memo, Date createTime, String createUser,
			Date lstUpdTime, String lstUpdUser, Long jpaVersion,
			String subTerminalType, String contrNbr, String mobileNumber,
			String refNbr, String contactChnl, String serviceId,
			String merchandiseOrder, String responseCode,
			String responseMessage, String terminalDevice,
			BigDecimal premiumAmt, Character premiumInd, BigDecimal loanAmt,
			String couponId, Character offsetType, Long term,
			String loanProdGroup, String proofId, String paymentChannel,
			Integer loanAgainTimes, String payTerms) {
		this.org = org;
		this.channelId = channelId;
		this.logKv = logKv;
		this.acctNbr = acctNbr;
		this.acctType = acctType;
		this.commandType = commandType;
		this.orderBrief = orderBrief;
		this.orderStatus = orderStatus;
		this.orderTime = orderTime;
		this.orberFailTime = orberFailTime;
		this.merId = merId;
		this.merName = merName;
		this.productType = productType;
		this.txnType = txnType;
		this.txnAmt = txnAmt;
		this.currency = currency;
		this.openBankId = openBankId;
		this.openBank = openBank;
		this.cardType = cardType;
		this.cardNo = cardNo;
		this.usrName = usrName;
		this.certType = certType;
		this.certId = certId;
		this.purpose = purpose;
		this.priv1 = priv1;
		this.state = state;
		this.city = city;
		this.subBank = subBank;
		this.flag = flag;
		this.guarantyId = guarantyId;
		this.status = status;
		this.code = code;
		this.message = message;
		this.dueBillNo = dueBillNo;
		this.businessDate = businessDate;
		this.sendTime = sendTime;
		this.oriOrderId = oriOrderId;
		this.setupDate = setupDate;
		this.optDatetime = optDatetime;
		this.loanUsage = loanUsage;
		this.payChannelId = payChannelId;
		this.payBizCode = payBizCode;
		this.successAmt = successAmt;
		this.failureAmt = failureAmt;
		this.onlineFlag = onlineFlag;
		this.requestTime = requestTime;
		this.servicesn = servicesn;
		this.authTxnTerminal = authTxnTerminal;
		this.acqId = acqId;
		this.matchInd = matchInd;
		this.comparedInd = comparedInd;
		this.errInd = errInd;
		this.memo = memo;
		this.createTime = createTime;
		this.createUser = createUser;
		this.lstUpdTime = lstUpdTime;
		this.lstUpdUser = lstUpdUser;
		this.jpaVersion = jpaVersion;
		this.subTerminalType = subTerminalType;
		this.contrNbr = contrNbr;
		this.mobileNumber = mobileNumber;
		this.refNbr = refNbr;
		this.contactChnl = contactChnl;
		this.serviceId = serviceId;
		this.merchandiseOrder = merchandiseOrder;
		this.responseCode = responseCode;
		this.responseMessage = responseMessage;
		this.terminalDevice = terminalDevice;
		this.premiumAmt = premiumAmt;
		this.premiumInd = premiumInd;
		this.loanAmt = loanAmt;
		this.couponId = couponId;
		this.offsetType = offsetType;
		this.term = term;
		this.loanProdGroup = loanProdGroup;
		this.proofId = proofId;
		this.paymentChannel = paymentChannel;
		this.loanAgainTimes = loanAgainTimes;
		this.payTerms = payTerms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER_ID", unique = true, nullable = false)
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "ORG", length = 12)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "CHANNEL_ID", length = 10)
	public String getChannelId() {
		return this.channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	@Column(name = "LOG_KV")
	public Long getLogKv() {
		return this.logKv;
	}

	public void setLogKv(Long logKv) {
		this.logKv = logKv;
	}

	@Column(name = "ACCT_NBR")
	public Long getAcctNbr() {
		return this.acctNbr;
	}

	public void setAcctNbr(Long acctNbr) {
		this.acctNbr = acctNbr;
	}

	@Column(name = "ACCT_TYPE", length = 1)
	public Character getAcctType() {
		return this.acctType;
	}

	public void setAcctType(Character acctType) {
		this.acctType = acctType;
	}

	@Column(name = "COMMAND_TYPE", length = 3)
	public String getCommandType() {
		return this.commandType;
	}

	public void setCommandType(String commandType) {
		this.commandType = commandType;
	}

	@Column(name = "ORDER_BRIEF", length = 400)
	public String getOrderBrief() {
		return this.orderBrief;
	}

	public void setOrderBrief(String orderBrief) {
		this.orderBrief = orderBrief;
	}

	@Column(name = "ORDER_STATUS", length = 1)
	public Character getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Character orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDER_TIME", length = 19)
	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORBER_FAIL_TIME", length = 19)
	public Date getOrberFailTime() {
		return this.orberFailTime;
	}

	public void setOrberFailTime(Date orberFailTime) {
		this.orberFailTime = orberFailTime;
	}

	@Column(name = "MER_ID", length = 32)
	public String getMerId() {
		return this.merId;
	}

	public void setMerId(String merId) {
		this.merId = merId;
	}

	@Column(name = "MER_NAME", length = 80)
	public String getMerName() {
		return this.merName;
	}

	public void setMerName(String merName) {
		this.merName = merName;
	}

	@Column(name = "PRODUCT_TYPE", length = 10)
	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	@Column(name = "TXN_TYPE", length = 20)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Column(name = "TXN_AMT", precision = 15)
	public BigDecimal getTxnAmt() {
		return this.txnAmt;
	}

	public void setTxnAmt(BigDecimal txnAmt) {
		this.txnAmt = txnAmt;
	}

	@Column(name = "CURRENCY", length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "OPEN_BANK_ID", length = 10)
	public String getOpenBankId() {
		return this.openBankId;
	}

	public void setOpenBankId(String openBankId) {
		this.openBankId = openBankId;
	}

	@Column(name = "OPEN_BANK", length = 100)
	public String getOpenBank() {
		return this.openBank;
	}

	public void setOpenBank(String openBank) {
		this.openBank = openBank;
	}

	@Column(name = "CARD_TYPE", length = 1)
	public Character getCardType() {
		return this.cardType;
	}

	public void setCardType(Character cardType) {
		this.cardType = cardType;
	}

	@Column(name = "CARD_NO", length = 32)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "USR_NAME", length = 100)
	public String getUsrName() {
		return this.usrName;
	}

	public void setUsrName(String usrName) {
		this.usrName = usrName;
	}

	@Column(name = "CERT_TYPE", length = 2)
	public String getCertType() {
		return this.certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	@Column(name = "CERT_ID", length = 25)
	public String getCertId() {
		return this.certId;
	}

	public void setCertId(String certId) {
		this.certId = certId;
	}

	@Column(name = "PURPOSE", length = 25)
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Column(name = "PRIV1", length = 120)
	public String getPriv1() {
		return this.priv1;
	}

	public void setPriv1(String priv1) {
		this.priv1 = priv1;
	}

	@Column(name = "STATE", length = 80)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "CITY", length = 80)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "SUB_BANK", length = 200)
	public String getSubBank() {
		return this.subBank;
	}

	public void setSubBank(String subBank) {
		this.subBank = subBank;
	}

	@Column(name = "FLAG", length = 2)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "GUARANTY_ID", length = 32)
	public String getGuarantyId() {
		return this.guarantyId;
	}

	public void setGuarantyId(String guarantyId) {
		this.guarantyId = guarantyId;
	}

	@Column(name = "STATUS", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CODE", length = 8)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "MESSAGE", length = 64)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "DUE_BILL_NO", length = 32)
	public String getDueBillNo() {
		return this.dueBillNo;
	}

	public void setDueBillNo(String dueBillNo) {
		this.dueBillNo = dueBillNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BUSINESS_DATE", length = 10)
	public Date getBusinessDate() {
		return this.businessDate;
	}

	public void setBusinessDate(Date businessDate) {
		this.businessDate = businessDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SEND_TIME", length = 10)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "ORI_ORDER_ID")
	public Long getOriOrderId() {
		return this.oriOrderId;
	}

	public void setOriOrderId(Long oriOrderId) {
		this.oriOrderId = oriOrderId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SETUP_DATE", length = 10)
	public Date getSetupDate() {
		return this.setupDate;
	}

	public void setSetupDate(Date setupDate) {
		this.setupDate = setupDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPT_DATETIME", length = 19)
	public Date getOptDatetime() {
		return this.optDatetime;
	}

	public void setOptDatetime(Date optDatetime) {
		this.optDatetime = optDatetime;
	}

	@Column(name = "LOAN_USAGE", length = 2)
	public String getLoanUsage() {
		return this.loanUsage;
	}

	public void setLoanUsage(String loanUsage) {
		this.loanUsage = loanUsage;
	}

	@Column(name = "PAY_CHANNEL_ID", length = 3)
	public String getPayChannelId() {
		return this.payChannelId;
	}

	public void setPayChannelId(String payChannelId) {
		this.payChannelId = payChannelId;
	}

	@Column(name = "PAY_BIZ_CODE", length = 4)
	public String getPayBizCode() {
		return this.payBizCode;
	}

	public void setPayBizCode(String payBizCode) {
		this.payBizCode = payBizCode;
	}

	@Column(name = "SUCCESS_AMT", precision = 15)
	public BigDecimal getSuccessAmt() {
		return this.successAmt;
	}

	public void setSuccessAmt(BigDecimal successAmt) {
		this.successAmt = successAmt;
	}

	@Column(name = "FAILURE_AMT", precision = 15)
	public BigDecimal getFailureAmt() {
		return this.failureAmt;
	}

	public void setFailureAmt(BigDecimal failureAmt) {
		this.failureAmt = failureAmt;
	}

	@Column(name = "ONLINE_FLAG", length = 1)
	public Character getOnlineFlag() {
		return this.onlineFlag;
	}

	public void setOnlineFlag(Character onlineFlag) {
		this.onlineFlag = onlineFlag;
	}

	@Column(name = "REQUEST_TIME", length = 14)
	public String getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(String requestTime) {
		this.requestTime = requestTime;
	}

	@Column(name = "SERVICESN", length = 32)
	public String getServicesn() {
		return this.servicesn;
	}

	public void setServicesn(String servicesn) {
		this.servicesn = servicesn;
	}

	@Column(name = "AUTH_TXN_TERMINAL", length = 40)
	public String getAuthTxnTerminal() {
		return this.authTxnTerminal;
	}

	public void setAuthTxnTerminal(String authTxnTerminal) {
		this.authTxnTerminal = authTxnTerminal;
	}

	@Column(name = "ACQ_ID", length = 8)
	public String getAcqId() {
		return this.acqId;
	}

	public void setAcqId(String acqId) {
		this.acqId = acqId;
	}

	@Column(name = "MATCH_IND", length = 1)
	public Character getMatchInd() {
		return this.matchInd;
	}

	public void setMatchInd(Character matchInd) {
		this.matchInd = matchInd;
	}

	@Column(name = "COMPARED_IND", length = 1)
	public Character getComparedInd() {
		return this.comparedInd;
	}

	public void setComparedInd(Character comparedInd) {
		this.comparedInd = comparedInd;
	}

	@Column(name = "ERR_IND", length = 1)
	public Character getErrInd() {
		return this.errInd;
	}

	public void setErrInd(Character errInd) {
		this.errInd = errInd;
	}

	@Column(name = "MEMO", length = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CREATE_USER", length = 32)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPD_TIME", length = 19)
	public Date getLstUpdTime() {
		return this.lstUpdTime;
	}

	public void setLstUpdTime(Date lstUpdTime) {
		this.lstUpdTime = lstUpdTime;
	}

	@Column(name = "LST_UPD_USER", length = 32)
	public String getLstUpdUser() {
		return this.lstUpdUser;
	}

	public void setLstUpdUser(String lstUpdUser) {
		this.lstUpdUser = lstUpdUser;
	}

	@Column(name = "JPA_VERSION", precision = 10, scale = 0)
	public Long getJpaVersion() {
		return this.jpaVersion;
	}

	public void setJpaVersion(Long jpaVersion) {
		this.jpaVersion = jpaVersion;
	}

	@Column(name = "SUB_TERMINAL_TYPE", length = 10)
	public String getSubTerminalType() {
		return this.subTerminalType;
	}

	public void setSubTerminalType(String subTerminalType) {
		this.subTerminalType = subTerminalType;
	}

	@Column(name = "CONTR_NBR", length = 50)
	public String getContrNbr() {
		return this.contrNbr;
	}

	public void setContrNbr(String contrNbr) {
		this.contrNbr = contrNbr;
	}

	@Column(name = "MOBILE_NUMBER", length = 20)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "REF_NBR", length = 32)
	public String getRefNbr() {
		return this.refNbr;
	}

	public void setRefNbr(String refNbr) {
		this.refNbr = refNbr;
	}

	@Column(name = "CONTACT_CHNL", length = 32)
	public String getContactChnl() {
		return this.contactChnl;
	}

	public void setContactChnl(String contactChnl) {
		this.contactChnl = contactChnl;
	}

	@Column(name = "SERVICE_ID", length = 32)
	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "MERCHANDISE_ORDER", length = 32)
	public String getMerchandiseOrder() {
		return this.merchandiseOrder;
	}

	public void setMerchandiseOrder(String merchandiseOrder) {
		this.merchandiseOrder = merchandiseOrder;
	}

	@Column(name = "RESPONSE_CODE", length = 8)
	public String getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	@Column(name = "RESPONSE_MESSAGE", length = 250)
	public String getResponseMessage() {
		return this.responseMessage;
	}

	public void setResponseMessage(String responseMessage) {
		this.responseMessage = responseMessage;
	}

	@Column(name = "TERMINAL_DEVICE", length = 32)
	public String getTerminalDevice() {
		return this.terminalDevice;
	}

	public void setTerminalDevice(String terminalDevice) {
		this.terminalDevice = terminalDevice;
	}

	@Column(name = "PREMIUM_AMT", precision = 15)
	public BigDecimal getPremiumAmt() {
		return this.premiumAmt;
	}

	public void setPremiumAmt(BigDecimal premiumAmt) {
		this.premiumAmt = premiumAmt;
	}

	@Column(name = "PREMIUM_IND", length = 1)
	public Character getPremiumInd() {
		return this.premiumInd;
	}

	public void setPremiumInd(Character premiumInd) {
		this.premiumInd = premiumInd;
	}

	@Column(name = "LOAN_AMT", precision = 15)
	public BigDecimal getLoanAmt() {
		return this.loanAmt;
	}

	public void setLoanAmt(BigDecimal loanAmt) {
		this.loanAmt = loanAmt;
	}

	@Column(name = "COUPON_ID", length = 32)
	public String getCouponId() {
		return this.couponId;
	}

	public void setCouponId(String couponId) {
		this.couponId = couponId;
	}

	@Column(name = "OFFSET_TYPE", length = 1)
	public Character getOffsetType() {
		return this.offsetType;
	}

	public void setOffsetType(Character offsetType) {
		this.offsetType = offsetType;
	}

	@Column(name = "TERM")
	public Long getTerm() {
		return this.term;
	}

	public void setTerm(Long term) {
		this.term = term;
	}

	@Column(name = "LOAN_PROD_GROUP", length = 20)
	public String getLoanProdGroup() {
		return this.loanProdGroup;
	}

	public void setLoanProdGroup(String loanProdGroup) {
		this.loanProdGroup = loanProdGroup;
	}

	@Column(name = "PROOF_ID", length = 50)
	public String getProofId() {
		return this.proofId;
	}

	public void setProofId(String proofId) {
		this.proofId = proofId;
	}

	@Column(name = "PAYMENT_CHANNEL", length = 40)
	public String getPaymentChannel() {
		return this.paymentChannel;
	}

	public void setPaymentChannel(String paymentChannel) {
		this.paymentChannel = paymentChannel;
	}

	@Column(name = "LOAN_AGAIN_TIMES", precision = 7, scale = 0)
	public Integer getLoanAgainTimes() {
		return this.loanAgainTimes;
	}

	public void setLoanAgainTimes(Integer loanAgainTimes) {
		this.loanAgainTimes = loanAgainTimes;
	}

	@Column(name = "PAY_TERMS", length = 64)
	public String getPayTerms() {
		return this.payTerms;
	}

	public void setPayTerms(String payTerms) {
		this.payTerms = payTerms;
	}

}
