package com.zyl.jpa.domain;

// Generated 2017-5-5 17:28:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import com.zyl.jpa.enums.GomeType;

/**
 * ZylGomeTest generated by hbm2java
 */
@Entity
@Table(name = "zyl_gome_test")
public class ZylGomeTest implements java.io.Serializable {

	private static final long serialVersionUID = 85213390162575902L;
	private String uuid;
	private String name;
	private Short age;
	private GomeType gometype;
	private Long num;
	private String comment;
	private BigDecimal money;
	private Integer jpaversion;

	public ZylGomeTest() {
	}

	public ZylGomeTest(String uuid) {
		this.uuid = uuid;
	}

	public ZylGomeTest(String uuid, String name, Short age, GomeType gometype,
			Long num, String comment, BigDecimal money, Integer jpaversion) {
		this.uuid = uuid;
		this.name = name;
		this.age = age;
		this.gometype = gometype;
		this.num = num;
		this.comment = comment;
		this.money = money;
		this.jpaversion = jpaversion;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false, length = 50)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "name", length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age")
	public Short getAge() {
		return this.age;
	}

	public void setAge(Short age) {
		this.age = age;
	}

	@Column(name = "gometype", length = 10)
	@Enumerated(value = EnumType.STRING)  
	public GomeType getGometype() {
		return this.gometype;
	}

	public void setGometype(GomeType gometype) {
		this.gometype = gometype;
	}

	@Column(name = "num")
	public Long getNum() {
		return this.num;
	}

	public void setNum(Long num) {
		this.num = num;
	}

	@Column(name = "comment", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "money", precision = 5)
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Column(name = "jpaversion")
	@Version
	public Integer getJpaversion() {
		return this.jpaversion;
	}

	public void setJpaversion(Integer jpaversion) {
		this.jpaversion = jpaversion;
	}

	@Override
	public String toString() {
		return "ZylGomeTest [uuid=" + uuid + ", name=" + name + ", age=" + age
				+ ", gometype=" + gometype + ", num=" + num + ", comment="
				+ comment + ", money=" + money + ", jpaversion=" + jpaversion
				+ "]";
	}

	
}
