package com.zyl.jpa.domain;

// Generated 2017-3-21 11:50:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ZylGome generated by hbm2java
 */
@Entity
@Table(name = "zyl_gome", catalog = "test")
public class ZylGome implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer age;
	private String card;
	private String uuid;
	private Character v;

	public ZylGome() {
	}

	public ZylGome(String name, Integer age, String card, String uuid,
			Character v) {
		this.name = name;
		this.age = age;
		this.card = card;
		this.uuid = uuid;
		this.v = v;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "card", length = 10)
	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	@Column(name = "uuid", length = 50)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "v", length = 1)
	public Character getV() {
		return this.v;
	}

	public void setV(Character v) {
		this.v = v;
	}

}
